---
- name: Deploy to webservers
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install pip with packages
      include_role:
        name: geerlingguy.pip

    - name: Create default containers
      docker_container:
        name: redmine
        image: redmine:4.2.1
        recreate: yes
        pull: yes
        ports:
          - 3000:3000
        state: started
        env:
          REDMINE_DB_DATABASE: "{{ REDMINE_DB_DATABASE }}"
          REDMINE_DB_POSTGRES: "{{ REDMINE_DB_POSTGRES }}"
          REDMINE_DB_USERNAME: "{{ REDMINE_DB_USERNAME }}"
          REDMINE_DB_PASSWORD: "{{ REDMINE_DB_PASSWORD }}"
          REDMINE_DB_PORT: "{{ REDMINE_DB_PORT | int }}"

    - name: Setting up Datadog agent
      include_role:
        name: datadog.datadog
