
datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: lvl2_project_status
        url: http://localhost:3000
        timeout: 5
        method: GET

datadog_api_key: "{{ vault_datadog_api_key }}"
